name = "CharacteristicMappingMethod"
uuid = "b86d1b17-7542-4a34-9cdf-28cc826a8044"
authors = ["Pierre Navaro <pierre.navaro@math.cnrs.fr>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Parameters = "0.12.3"
Test = "1.11.0"
